display_name: "Vein Miner"
description: "Breaks all similar blocks in a %level% radius"
type: tool
rarity: mythical
max_level: 5
item: DIAMOND_PICKAXE
trigger: on_break
effects:
  - id: vein_miner
    radius: %level%